// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ChassisSwitchBrake.h"
ChassisSwitchBrake::ChassisSwitchBrake() 
:on(true)
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ChassisSwitchBrake::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void ChassisSwitchBrake::Execute() {
	if(on)
	{
		RobotMap::chassisRightJaguar1->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		RobotMap::chassisRightJaguar2->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		RobotMap::chassisRightJaguar3->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		RobotMap::chassisLeftJaguar1->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		RobotMap::chassisLeftJaguar2->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		RobotMap::chassisLeftJaguar3->ConfigNeutralMode(CANJaguar::kNeutralMode_Coast);
		on = false;
	}
	else
	{
		RobotMap::chassisRightJaguar1->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		RobotMap::chassisRightJaguar2->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		RobotMap::chassisRightJaguar3->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		RobotMap::chassisLeftJaguar1->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		RobotMap::chassisLeftJaguar2->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		RobotMap::chassisLeftJaguar3->ConfigNeutralMode(CANJaguar::kNeutralMode_Brake);
		on = true;
	}
}
// Make this return true when this Command no longer needs to run execute()
bool ChassisSwitchBrake::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void ChassisSwitchBrake::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChassisSwitchBrake::Interrupted() {
}
