// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShooterWinchToSetpoint.h"
ShooterWinchToSetpoint::ShooterWinchToSetpoint() :
setpoint(0){
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::ultrasonicSystem);
}
// Called just before this Command runs the first time
void ShooterWinchToSetpoint::Initialize() {
	setpoint = Robot::robotPref->GetDouble("ShooterSetpoint", 0);
}
// Called repeatedly when this Command is scheduled to run
void ShooterWinchToSetpoint::Execute() {
	Robot::shooter->controller->SetSetpoint(setpoint);
	Robot::shooter->controller->Enable();
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterWinchToSetpoint::IsFinished() {
 	return ((Robot::ultrasonicSystem->rangeSample - (setpoint)) <= 0.25 &&
			(Robot::ultrasonicSystem->rangeSample - (setpoint)) >= -0.25);;
}
// Called once after isFinished returns true
void ShooterWinchToSetpoint::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterWinchToSetpoint::Interrupted() {
}
