// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmPivotSwitch.h"
#include "Commands/AutoDrive.h"
#include "Commands/AutoOneBall.h"
#include "Commands/ChassisReverseDrive.h"
#include "Commands/ChassisSwitchBrake.h"
#include "Commands/ChassisTankDrive.h"
#include "Commands/Compress.h"
#include "Commands/IntakeMaintain.h"
#include "Commands/IntakeOuttake.h"
#include "Commands/IntakeSwitchRoller.h"
#include "Commands/IntakeSwitchSolenoid.h"
#include "Commands/Shift.h"
#include "Commands/ShooterEngage.h"
#include "Commands/ShooterManualWinch.h"
#include "Commands/ShooterShoot.h"
#include "Commands/ShooterWinchToSetpoint.h"
#include "Commands/UnderglowOn.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driver = new Joystick(1);
	
	driverLBumper = new JoystickButton(driver, 5);
	driverLBumper->WhenPressed(new ChassisSwitchBrake());
	driverRBumper = new JoystickButton(driver, 6);
	driverRBumper->WhenPressed(new ChassisReverseDrive());
	driverB = new JoystickButton(driver, 2);
	driverB->WhenPressed(new AutoDrive());
	driverRStick = new JoystickButton(driver, 10);
	driverRStick->WhenPressed(new Shift());
	coDriver = new Joystick(2);
	
	coDriverRStick = new JoystickButton(coDriver, 10);
	coDriverRStick->WhenPressed(new ShooterWinchToSetpoint());
	coDriverRBumper = new JoystickButton(coDriver, 6);
	coDriverRBumper->WhenPressed(new IntakeSwitchSolenoid());
	coDriverButtonX = new JoystickButton(coDriver, 3);
	coDriverButtonX->WhileHeld(new IntakeOuttake());
	coDriverButtonA = new JoystickButton(coDriver, 1);
	coDriverButtonA->WhenPressed(new IntakeSwitchRoller());
     
        // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	coDriverRThrottle = new ThrottleButton(coDriver, 3, -0.75, ThrottleButton::kNegative);
	coDriverRThrottle->WhenPressed(new ShooterShoot());
	coDriverRThrottle->WhenReleased(new ShooterEngage());
	coDriverLThrottle = new ThrottleButton(coDriver, 3, 0.75);
	coDriverLThrottle->WhenPressed(new ArmPivotSwitch());
	SmartDashboard::PutData("ChassisTankDrive", new ChassisTankDrive());
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriver() {
	return driver;
}
Joystick* OI::getCoDriver() {
	return coDriver;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
