// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/ArmPivotSwitch.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ChassisTankDrive.h"
#include "Commands/Compress.h"
#include "Commands/IntakeMaintain.h"
#include "Commands/IntakeOuttake.h"
#include "Commands/IntakeSwitchRoller.h"
#include "Commands/IntakeSwitchSolenoid.h"
#include "Commands/Shift.h"
#include "Commands/ShooterManualWinch.h"
#include "Commands/ShooterShoot.h"
#include "Commands/UltrasonicGetSample.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driver = new Joystick(1);
	
	driverRStick = new JoystickButton(driver, 10);
	driverRStick->WhenPressed(new Shift());
	driverStart = new JoystickButton(driver, 8);
	driverStart->WhenPressed(new ShooterShoot());
	driverRBumper = new JoystickButton(driver, 6);
	driverRBumper->WhenPressed(new IntakeSwitchSolenoid());
	driverLBumper = new JoystickButton(driver, 5);
	driverLBumper->WhenPressed(new ArmPivotSwitch());
	driverButtonY = new JoystickButton(driver, 4);
	driverButtonY->WhileHeld(new ShooterManualWinch());
	driverButtonX = new JoystickButton(driver, 3);
	driverButtonX->WhileHeld(new IntakeOuttake());
	driverButtonA = new JoystickButton(driver, 1);
	driverButtonA->WhenPressed(new IntakeSwitchRoller());
     
        // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriver() {
	return driver;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
