// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/IntakeSwitchRoller.h"
#include "Commands/IntakeSwitchSolenoid.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driverJoystick = new Joystick(1);
	
	dButtonB = new JoystickButton(driverJoystick, 2);
	dButtonB->WhenPressed(new IntakeSwitchRoller());
	driverButtonA = new JoystickButton(driverJoystick, 1);
	driverButtonA->WhenPressed(new IntakeSwitchSolenoid());
     
        // SmartDashboard Buttons
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	double distance = SmartDashboard::GetNumber("Distance");
	char buf[10];
	sprintf(buf, "%7.3f", distance);
	DriverStationLCD::GetInstance()->Printf(DriverStationLCD::kUser_Line1, 1, buf);
	DriverStationLCD::GetInstance()->UpdateLCD();
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriverJoystick() {
	return driverJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
