// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
#include "ThrottleButton.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* driver;
	JoystickButton* driverLBumper;
	JoystickButton* driverRBumper;
	JoystickButton* driverB;
	JoystickButton* driverRStick;
	Joystick* coDriver;
	JoystickButton* coDriverRStick;
	JoystickButton* coDriverRBumper;
	JoystickButton* coDriverButtonX;
	JoystickButton* coDriverButtonA;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* coDriverLStick;
	ThrottleButton* coDriverRThrottle;
	ThrottleButton* coDriverLThrottle;
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getCoDriver();
	Joystick* getDriver();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
