// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Encoder* RobotMap::chassisLeftEncoder = NULL;
Encoder* RobotMap::chassisRightEncoder = NULL;
Compressor* RobotMap::compressorSystemCompressor = NULL;
CANJaguar* RobotMap::intakeRoller = NULL;
DoubleSolenoid* RobotMap::intakeSolenoid = NULL;
DoubleSolenoid* RobotMap::shifterShifter = NULL;
DoubleSolenoid* RobotMap::armPivotSolenoid = NULL;
DoubleSolenoid* RobotMap::shootershooterClutch = NULL;
CANJaguar* RobotMap::shootershooterWinch1 = NULL;
CANJaguar* RobotMap::shootershooterWinch2 = NULL;
Ultrasonic* RobotMap::ultrasonicSystemUltrasonic = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::chassisLeftJaguar1 = NULL;
CANJaguar* RobotMap::chassisRightJaguar1 = NULL;
CANJaguar* RobotMap::chassisLeftJaguar2 = NULL;
CANJaguar* RobotMap::chassisRightJaguar2 = NULL;
CANJaguar* RobotMap::chassisLeftJaguar3 = NULL;
CANJaguar* RobotMap::chassisRightJaguar3 = NULL;
TripleMotor* RobotMap::chassisLeftDrive = NULL;
TripleMotor* RobotMap::chassisRightDrive = NULL;
RobotDrive* RobotMap::chassisRobotDrive = NULL;

DoubleMotor* RobotMap::shootershooterWinch = NULL;
void RobotMap::init() {
	chassisRightJaguar1 = new CANJaguar(2);
	chassisRightJaguar2 = new CANJaguar(3);
	chassisRightJaguar3 = new CANJaguar(4);
	
	chassisLeftJaguar1 = new CANJaguar(5);
	chassisLeftJaguar2 = new CANJaguar(6);
	chassisLeftJaguar3 = new CANJaguar(7);
	
	chassisRightDrive = new TripleMotor(chassisRightJaguar1,
							chassisRightJaguar2,chassisRightJaguar3);
	
	chassisLeftDrive = new TripleMotor(chassisLeftJaguar1,
							chassisLeftJaguar2,chassisLeftJaguar3);
	chassisRobotDrive = new RobotDrive(chassisLeftDrive, chassisRightDrive);
	
	chassisRobotDrive->SetSafetyEnabled(true);
        chassisRobotDrive->SetExpiration(0.1);
        chassisRobotDrive->SetSensitivity(0.5);
        chassisRobotDrive->SetMaxOutput(1.0);
        
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	chassisLeftEncoder = new Encoder(1, 4, 1, 5, false, Encoder::k4X);
	lw->AddSensor("Chassis", "LeftEncoder", chassisLeftEncoder);
	chassisLeftEncoder->SetDistancePerPulse(0.05);
        chassisLeftEncoder->SetPIDSourceParameter(Encoder::kDistance);
        chassisLeftEncoder->Start();
	chassisRightEncoder = new Encoder(1, 6, 1, 7, false, Encoder::k4X);
	lw->AddSensor("Chassis", "RightEncoder", chassisRightEncoder);
	chassisRightEncoder->SetDistancePerPulse(0.05);
        chassisRightEncoder->SetPIDSourceParameter(Encoder::kDistance);
        chassisRightEncoder->Start();
	compressorSystemCompressor = new Compressor(1, 3, 1, 1);
	
	
	intakeRoller = new CANJaguar(8);
	
	
	intakeSolenoid = new DoubleSolenoid(1, 1, 5);      
	
	
	shifterShifter = new DoubleSolenoid(1, 2, 6);      
	
	
	armPivotSolenoid = new DoubleSolenoid(1, 3, 7);      
	
	
	shootershooterClutch = new DoubleSolenoid(1, 4, 8);      
	
	
	shootershooterWinch1 = new CANJaguar(9);
	
	
	shootershooterWinch2 = new CANJaguar(10);
	
	
	ultrasonicSystemUltrasonic = new Ultrasonic(1, 1, 1, 2);
	lw->AddSensor("UltrasonicSystem", "Ultrasonic", ultrasonicSystemUltrasonic);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	
	shootershooterWinch = new DoubleMotor(shootershooterWinch1, shootershooterWinch2);
}
