// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* RobotMap::chassisRightBackJaguar = NULL;
CANJaguar* RobotMap::chassisLeftBackJaguar = NULL;
CANJaguar* RobotMap::chassisRightMiddleJaguar = NULL;
CANJaguar* RobotMap::chassisLeftMiddleJaguar = NULL;
CANJaguar* RobotMap::chassisRightFrontJaguar = NULL;
CANJaguar* RobotMap::chassisLeftFrontJaguar = NULL;
DoubleSolenoid* RobotMap::shifterShifter = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
RobotDrive* RobotMap::chassisRobotDrive = NULL;
TripleMotor* chassisLeftTripleMotor = NULL;
TripleMotor* chassisRightTripleMotor = NULL;
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	chassisRightBackJaguar = new CANJaguar(7);
	
	
	chassisLeftBackJaguar = new CANJaguar(6);
	
	
	chassisRightMiddleJaguar = new CANJaguar(5);
	
	
	chassisLeftMiddleJaguar = new CANJaguar(4);
	
	
	chassisRightFrontJaguar = new CANJaguar(3);
	
	
	chassisLeftFrontJaguar = new CANJaguar(2);
	
	
	shifterShifter = new DoubleSolenoid(1, 1, 2);      
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	
	chassisRobotDrive = new RobotDrive(chassisLeftTripleMotor, chassisRightTripleMotor);
	
	
	chassisLeftTripleMotor = new TripleMotor(chassisLeftBackJaguar,
	    		                             chassisLeftMiddleJaguar,
	    		                             chassisLeftFrontJaguar);
	    
	chassisRightTripleMotor = new TripleMotor(chassisRightBackJaguar,
	                                          chassisRightMiddleJaguar,
	                                          chassisRightFrontJaguar);
}
